### ISSUE TITLE
Unable to Specify AWS Bedrock Region

### ISSUE THREAD

**Issue by shnskfjwr** [Codium-ai/pr-agent#1050]
## Description
When specifying [aws] bedrock_region = "us-east-1" either through environment variables or in the .secrets.toml file, the requests are still being sent to the us-west-2 endpoint.
I have not registered any Bedrock models in the us-west-2 region, so I am unable to verify the functionality in that region.

## Steps to Reproduce
1. Set [aws] bedrock_region = "us-east-1" in the environment variables or in the .secrets.toml file.
1. Observe that requests are directed to the us-west-2 endpoint instead of us-east-1.

## Expected Behavior
Requests should be sent to the us-east-1 endpoint when bedrock_region is set to us-east-1.

## Actual Behavior
Requests are being sent to the us-west-2 endpoint despite the bedrock_region setting.

## GitHubActions Logs
```
06:04:01 - LiteLLM:ERROR: main.py:399 - litellm.acompletion(): Exception occured - {"message":"The provided model identifier is invalid."}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/bedrock_httpx.py", line 1612, in async_completion
    response = await client.post(api_base, headers=headers, data=data)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/custom_httpx/http_handler.py", line 112, in post
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/custom_httpx/http_handler.py", line 94, in post
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://bedrock-runtime.us-west-2.amazonaws.com/model/anthropic.claude-3-5-sonnet-20240620-v1:0/converse'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/litellm/main.py", line [37](https://github.com/hands-lab/coe-sample-pr-agent/actions/runs/10035518963/job/27731660664#step:6:38)8, in acompletion
    response = await init_response
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/bedrock_httpx.py", line 1616, in async_completion
    raise BedrockError(status_code=error_code, message=err.response.text)
litellm.llms.bedrock.BedrockError: {"message":"The provided model identifier is invalid."}


Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.
```

## GitHub Actions Definition
```
      - id: pr-agent
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Amazon Bedrock
          CONFIG.MODEL: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
          CONFIG.MODEL_TURBO: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
          CONFIG.FALLBACK_MODEL: bedrock/anthropic.claude-v2:1
          LITELLM.DROP_PARAMS: true
          AWS.BEDROCK_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PR_REVIEWER.EXTRA_INSTRUCTIONS: ${{ env.REVIEW_PROMPT }}
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: ${{ env.DESCRIBE_PROMPT }}
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: ${{env.IMPROVE_PROMPT}}

```

**Comment by mrT23** [comment]
litellm changed the syntax:

https://litellm.vercel.app/docs/providers/bedrock

`AWS_REGION_NAME `

**Comment by shnskfjwr** [comment]
This code worked correctly. Thank you!

```
      - id: pr-agent
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Amazon Bedrock
          CONFIG.MODEL: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
          CONFIG.MODEL_TURBO: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
          CONFIG.FALLBACK_MODEL: bedrock/anthropic.claude-v2:1
          LITELLM.DROP_PARAMS: true
          AWS_REGION_NAME: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PR_REVIEWER.EXTRA_INSTRUCTIONS: ${{ env.REVIEW_PROMPT }}
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: ${{ env.DESCRIBE_PROMPT }}
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: ${{env.IMPROVE_PROMPT}}
```

I would appreciate it if you could update the documentation for future users.

**Comment by shnskfjwr** [comment]
That's true. I created a PullRequest.
https://github.com/Codium-ai/pr-agent/pull/1052
