### ISSUE TITLE
Unable to run on BitBucket Cloud Pipeline: Multiple Errors

### ISSUE THREAD

**Issue by jagberg-compareclub** [Codium-ai/pr-agent#1150]
Im setting up Codium for the first time in BitBucket Cloud and getting a few errors but its not clear what the underlying issue is. Ive done the following:
* Setup a BitBucket Access Key with all permissions set (Ill limit this once its working)
* Setup OpenAI Keys (Tried the User and Project Keys)
* Committed this to the master branch
* Created a PR after every change just to ensure the latest configs are used.

**Repo Variables**
<img src="https://github.com/user-attachments/assets/a70213a1-60a5-41b6-854c-1b3009757430" width="350">

**PR**
<img src="https://github.com/user-attachments/assets/00565ac0-1793-44b4-9b17-c88fc23f5bf3" width="350">

**Docker Log**

[pipelineLog-{b7b9183b-aa13-4d62-b9f5-8077e44301ca}-{af72d680-5242-48dc-b6f0-3f795e1e1b8d}.txt](https://github.com/user-attachments/files/16633197/pipelineLog-.b7b9183b-aa13-4d62-b9f5-8077e44301ca.-.af72d680-5242-48dc-b6f0-3f795e1e1b8d.txt)

**Build Log**

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.
2024-08-16 05:11:48.639 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:154 - Error during OpenAI inference: 
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
[LiteLLM.Info](http://litellm.info/): If you need to debug this error, use `litellm.set_verbose=True'.
2024-08-16 05:11:48.730 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:154 - Error during OpenAI inference: 
2024-08-16 05:11:48.735 | WARN
[pipelineLog-{b7b9183b-aa13-4d62-b9f5-8077e44301ca}-{af72d680-5242-48dc-b6f0-3f795e1e1b8d}.txt](https://github.com/user-attachments/files/16633179/pipelineLog-.b7b9183b-aa13-4d62-b9f5-8077e44301ca.-.af72d680-5242-48dc-b6f0-3f795e1e1b8d.txt)
ING  | pr_agent.algo.pr_processing:retry_with_fallback_models:331 - Failed to generate prediction with gpt-4-0125-preview: Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/litellm/main.py", line 401, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/litellm/llms/openai.py", line 1124, in acompletion
    raise e
  File "/usr/local/lib/python3.12/site-packages/litellm/llms/openai.py", line 1079, in acompletion
    headers, response = await self.make_openai_chat_completion_request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/litellm/llms/openai.py", line 781, in make_openai_chat_completion_request
    raise e
  File "/usr/local/lib/python3.12/site-packages/litellm/llms/openai.py", line 772, in make_openai_chat_completion_request
    await openai_aclient.chat.completions.with_raw_response.create(
  File "/usr/local/lib/python3.12/site-packages/openai/_legacy_response.py", line 367, in wrapped
    return cast(LegacyAPIResponse[R], await func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 1339, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1815, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1509, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1610, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-0125-preview` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/pr_agent/algo/ai_handlers/litellm_ai_handler.py", line 152, in chat_completion
    response = await acompletion(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/litellm/utils.py", line 1579, in wrapper_async
    raise e
  File "/usr/local/lib/python3.12/site-packages/litellm/utils.py", line 1399, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/litellm/main.py", line 424, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/litellm/utils.py", line 8301, in exception_type
    raise e
  File "/usr/local/lib/python3.12/site-packages/litellm/utils.py", line 6558, in exception_type
    raise NotFoundError(
litellm.exceptions.NotFoundError: litellm.NotFoundError: OpenAIException - The model `gpt-4-0125-preview` does not exist or you do not have access to it.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/pr_agent/algo/pr_processing.py", line 329, in retry_with_fallback_models
    return await f(model)
           ^^^^^^^^^^^^^^
  File "/app/pr_agent/tools/pr_reviewer.py", line 159, in _prepare_prediction
    self.prediction = await self._get_prediction(model)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/pr_agent/tools/pr_reviewer.py", line 181, in _get_prediction
    response, finish_reason = await self.ai_handler.chat_completion(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7fd3485bd910 state=finished raised NotFoundError>]
2024-08-16 05:11:48.735 | ERROR    | pr_agent.tools.pr_reviewer:run:148 - Failed to review PR: RetryError[<Future at 0x7fd3485bd910 state=finished raised NotFoundError>]

**Comment by mrT23** [comment]
![image](https://github.com/user-attachments/assets/164b2e51-ad68-4f0b-b74d-b24b80db5e60)

**Comment by jagberg-compareclub** [comment]
> ![image](https://private-user-images.githubusercontent.com/21198860/358481492-164b2e51-ad68-4f0b-b74d-b24b80db5e60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODc1MjMsIm5iZiI6MTcyMzc4NzIyMywicGF0aCI6Ii8yMTE5ODg2MC8zNTg0ODE0OTItMTY0YjJlNTEtYWQ2OC00ZjBiLWI3NGQtYjI0YjgwZGI1ZTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA1NDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhODZjYjg5OGRiNzBkY2VmM2RjOWRmYTc3NjJiYTM2NWMyY2U2ZWU4NDk5YzAxNGQzY2Q4ZGEwYmU5ZmJkMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ngXen2rKQzo5I_R-XcJkSbh3RkJbCtrNVAgHTVGm56A)

I saw that as well but I couldnt find out how to enable this or choose a different model.

**Comment by mrT23** [comment]
we cannot debug your personal deployment

**Comment by jagberg-compareclub** [comment]
I setup GitHub and followed the standard installation with the same Open API Key and that worked perfectly. Is there anything else I can try to get this working? Ive also tried setting the environment variable to use a different model but I cant get that working. 

I tried:
`docker .... -e OPENAI.CONFIG_MODEL='gpt-3.5-turbo'... and
`docker .... -e CONFIG.MODEL='gpt-3.5-turbo'... 

Ive also tried an older docker image, all the way to v11 but no luck.

**Comment by mrT23** [comment]
Setting up local deployment may require effort and problem-solving.
If you struggle with it, you can try pr-agent pro, where installation is easier, among other benefits

https://pr-agent-docs.codium.ai/overview/pr_agent_pro/

**Comment by jagberg-compareclub** [comment]
I setup an Open API key using my organisations account and running it now works. Strange that using the same key works in GitHub but not BitBucket. Is there different logic for the models it chooses?

**Comment by mrT23** [comment]
no
