### ISSUE TITLE
Azure DevOps : too many values to unpack

### ISSUE THREAD

**Issue by davidrwanda** [Codium-ai/pr-agent#1209]
2024-09-09 07:32:33.004 | INFO     | pr_agent.algo.pr_processing:get_pr_diff:74 - Tokens: 855, total tokens under limit: 32000, returning full diff.
Traceback (most recent call last):
  File "/usr/local/bin/pr-agent", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/app/pr_agent/cli.py", line 88, in run
    result = asyncio.run(inner())
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/pr_agent/cli.py", line 79, in inner
t = await asyncio.create_task(PRAgent().handle_request(args.pr_url, [command] + args.rest))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/pr_agent/agent/pr_agent.py", line 96, in handle_request
    await command2class[action](pr_url, ai_handler=self.ai_handler, args=args).run()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/pr_agent/tools/pr_reviewer.py", line 57, in __init__
    self.pr_description, self.pr_description_files = (
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)

**Comment by mrT23** [comment]
thanks, should be fixed now

**Comment by davidrwanda** [comment]
Thanks
