### ISSUE TITLE
Improve fails with AttributeError on Azure DevOps when used with `commitable_code_suggestions=true`

### ISSUE THREAD

**Issue by danstis** [Codium-ai/pr-agent#1239]
I have found that using pr-agent on Azure DevOps fails with the following error when running improve with `commitable_code_suggestions=true`. This happens after it posts the comments with the commitable suggestions, then seems to attempt to remove the 'Generating PR code suggestions' comment:
```
2024-09-19 05:00:45.182 | ERROR    | pr_agent.tools.pr_code_suggestions:run:163 - Failed to generate code suggestions for PR, error: 'dict' object has no attribute 'delete'
Traceback (most recent call last):
  File "/app/pr_agent/tools/pr_code_suggestions.py", line 161, in run
    self.progress_response.delete()
AttributeError: 'dict' object has no attribute 'delete'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/pr_agent/cli.py", line 83, in <module>
    run()
  File "/app/pr_agent/cli.py", line 77, in run
    result = asyncio.run(PRAgent().handle_request(args.pr_url, [command] + args.rest))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/pr_agent/agent/pr_agent.py", line 96, in handle_request
    await command2class[action](pr_url, ai_handler=self.ai_handler, args=args).run()
  File "/app/pr_agent/tools/pr_code_suggestions.py", line 165, in run
    self.progress_response.delete()
AttributeError: 'dict' object has no attribute 'delete'
```

When run with `commitable_code_suggestions=false` this error does not occur.

**Comment by mrT23** [comment]
thanks, this should fix it:
https://github.com/Codium-ai/pr-agent/commit/08319f84920bb662bcc7fd863a4738ab5cc37eb6

**Comment by danstis** [comment]
I have tested and this change does indeed fix the issue.
Will this make it to a new published version of the docker images?

**Comment by mrT23** [comment]
the latest docker image already contains this change.
You can work against a SHA version if you prefer a "fixed" version

https://pr-agent-docs.codium.ai/installation/locally/#using-docker-image
