### ISSUE TITLE
I run the gitlab CI/CD, There is a error.

### ISSUE THREAD

**Issue by zhangjiuyang1993** [Codium-ai/pr-agent#1322]
The content of my .gitlab-ci.yml file is:
stages:

pr_agent
pr_agent_job:
stage: pr_agent
image:
name: codiumai/pr-agent:latest
entrypoint: ['/bin/bash', '-s']
script:
- cd /app
- echo "Running PR Agent action step"
- export MR_URL="$CI_MERGE_REQUEST_PROJECT_URL/merge_requests/$CI_MERGE_REQUEST_IID"
- echo "MR_URL=$MR_URL"
- export gitlab__url=$CI_SERVER_PROTOCOL://$CI_SERVER_FQDN
- export gitlab__PERSONAL_ACCESS_TOKEN=$GITLAB_PERSONAL_ACCESS_TOKEN
- export config__git_provider="gitlab"
- export openai__key=$OPENAI_KEY
- python -m pr_agent.cli --pr_url="$MR_URL" describe
- python -m pr_agent.cli --pr_url="$MR_URL" review
- python -m pr_agent.cli --pr_url="$MR_URL" improve
rules:
- if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

When I run the gitlab CI/CD, there is a error. The error is

**Comment by zhangjiuyang1993** [comment]
$ python -m pr_agent.cli --pr_url="$MR_URL" describe
Traceback (most recent call last):
  File "/app/pr_agent/git_providers/__init__.py", line 57, in get_git_provider_with_context
    git_provider = _GIT_PROVIDERS[provider_id](pr_url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/pr_agent/git_providers/gitlab_provider.py", line 45, in __init__
    self._set_merge_request(merge_request_url)
  File "/app/pr_agent/git_providers/gitlab_provider.py", line 63, in _set_merge_request
    self.mr = self._get_merge_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/pr_agent/git_providers/gitlab_provider.py", line 504, in _get_merge_request
    mr = self.gl.projects.get(self.id_project).mergerequests.get(self.id_mr)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gitlab/v4/objects/projects.py", line 860, in get
    return cast(Project, super().get(id=id, lazy=lazy, **kwargs))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gitlab/exceptions.py", line [33](http://gitlab.ops.haochezhu.club/datascience/lark-notify/-/jobs/113806#L33)6, in wrapped_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gitlab/mixins.py", line 122, in get
    server_data = self.gitlab.http_get(path, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gitlab/client.py", line 828, in http_get
    result = self.http_request(
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gitlab/client.py", line 725, in http_request
    result = self._backend.http_request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gitlab/_backends/requests_backend.py", line 123, in http_request
    response: requests.Response = self._client.request(
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line [36](http://gitlab.ops.haochezhu.club/datascience/lark-notify/-/jobs/113806#L36)7, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 444, in prepare_url
    raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
requests.exceptions.InvalidURL: Invalid URL 'http:///api/v4/projects/datascience%2Flark-notify': No host supplied
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/pr_agent/cli.py", line 94, in <module>
    run()
  File "/app/pr_agent/cli.py", line 88, in run
    result = asyncio.run(inner())
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/pr_agent/cli.py", line 79, in inner
    result = await asyncio.create_task(PRAgent().handle_request(args.pr_url, [command] + args.rest))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/pr_agent/agent/pr_agent.py", line [57](http://gitlab.ops.haochezhu.club/datascience/lark-notify/-/jobs/113806#L57), in handle_request
    apply_repo_settings(pr_url)
  File "/app/pr_agent/git_providers/utils.py", line 14, in apply_repo_settings
    git_provider = get_git_provider_with_context(pr_url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/pr_agent/git_providers/__init__.py", line [62](http://gitlab.ops.haochezhu.club/datascience/lark-notify/-/jobs/113806#L62), in get_git_provider_with_context
    raise ValueError(f"Failed to get git provider for {pr_url}") from e
ValueError: Failed to get git provider for http://gitlab.ops.haochezhu.club/datascience/lark-notify/merge_requests/2
what is the reason of the error?

**Comment by zhangjiuyang1993** [comment]
Is it because my GitLab address is: http://gitlab.ops.haochezhu.club/?

**Comment by zhangjiuyang1993** [comment]
my configuration.toml is:
[config]
# models
model="gpt-4-turbo-2024-04-09"
model_turbo="gpt-4o"
fallback_models=["gpt-4-0125-preview"]
# CLI
git_provider="gitlab"

**Comment by zhangjiuyang1993** [comment]
I change the .gitlab-ci.yml:
variables:
  CI_SERVER_PROTOCOL: "https"
  CI_SERVER_FQDN: "gitlab.ops.haochezhu.club"
stages:
  - pr_agent

pr_agent_job:
  stage: pr_agent
  image: 
    name: dockerpull.org/codiumai/pr-agent:latest
    entrypoint: ['/bin/bash', '-s']
  script:
    - cd /app
    - echo "Running PR Agent action step"
    - export MR_URL=""$CI_SERVER_PROTOCOL://$CI_SERVER_FQDN/datascience/lark-notify/merge_requests/$CI_MERGE_REQUEST_IID""
    - echo "MR_URL=$MR_URL"
    - export gitlab__url=$CI_SERVER_PROTOCOL://$CI_SERVER_FQDN
    - echo "gitlab__url=$gitlab__url"
    - export gitlab__PERSONAL_ACCESS_TOKEN=$GITLAB_PERSONAL_ACCESS_TOKEN 
    - export config__git_provider="gitlab"
    - export openai__key=$OPENAI_KEY
    - python -m pr_agent.cli --pr_url="$MR_URL" describe
    - python -m pr_agent.cli --pr_url="$MR_URL" review
    - python -m pr_agent.cli --pr_url="$MR_URL" improve
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
But a error occurs :
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gitlab.ops.haochezhu.club', port=443): Max retries exceeded with url: /api/v4/projects/datascience%2Flark-notify (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f33f7d3b290>: Failed to establish a new connection: [Errno 111] Connection refused'))
