### ISSUE TITLE
Unable to use Anthropic Model

### ISSUE THREAD

**Issue by cavinwela** [Codium-ai/pr-agent#1323]
Hi, I'm trying to test it on my local. I'm a bit confused on how to make it work with only an Anthropic Key, without providing openai key. 

The following is terminal my command: 
```
docker run --platform linux/amd64 --rm -it 
  -e config.model=anthropic/claude-3-5-sonnet-20240620 
  -e ANTHROPIC.KEY=...
  -e GITHUB.USER_TOKEN=...
  codiumai/pr-agent 
  --pr_url "$pr_url" "improve" 
  --pr_description.keep_original_user_title=true 
  --pr_code_suggestions.commitable_code_suggestions=true
```

These are the following output: 
```
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 6913, in exception_type
    message = original_exception.message
AttributeError: 'OpenAIError' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/pr_agent/algo/ai_handlers/litellm_ai_handler.py", line 145, in chat_completion
    response = await acompletion(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 3181, in wrapper_async
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 3017, in wrapper_async
    result = await original_function(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/litellm/main.py", line 296, in acompletion
    raise exception_type(
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 8182, in exception_type
    raise original_exception
  File "/usr/local/lib/python3.10/site-packages/litellm/main.py", line 283, in acompletion
    response = await init_response
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/openai.py", line 439, in acompletion
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/openai.py", line 402, in acompletion
    openai_aclient = AsyncOpenAI(
  File "/usr/local/lib/python3.10/site-packages/openai/_client.py", line 296, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/pr_agent/algo/pr_processing.py", line 272, in retry_with_fallback_models
    return await f(model)
  File "/app/pr_agent/tools/pr_code_suggestions.py", line 341, in _prepare_prediction_extended
    prediction_list = await asyncio.gather(
  File "/app/pr_agent/tools/pr_code_suggestions.py", line 175, in _get_prediction
    response, finish_reason = await self.ai_handler.chat_completion(model=model, temperature=0.2,
  File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/app/pr_agent/algo/ai_handlers/litellm_ai_handler.py", line 146, in chat_completion
    except (openai.APIError, openai.Timeout) as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by mrT23** [comment]
see https://qodo-merge-docs.qodo.ai/usage-guide/changing_a_model/#changing-a-model

**Comment by cavinwela** [comment]
> see https://qodo-merge-docs.qodo.ai/usage-guide/changing_a_model/#changing-a-model

I have made both configurations.toml and .secrets.toml, but same result with the command I have. 

Does this mean, that I have to deploy our own docker-image with the configs? 

Sorry, new to this. Command works with OPENAI.

**Comment by mrT23** [comment]
if you run via **pre-built docker**, do:

```
docker run --platform linux/amd64 --rm -it 
  -e config.model=anthropic/claude-3-5-sonnet-20240620 
  -e config.model_turbo=anthropic/claude-3-5-sonnet-20240620 
  -e config.fallback_models=['anthropic/claude-3-5-sonnet-20240620']
  ...
```

or something similar

**Comment by cavinwela** [comment]
Thank you @mrT23! 
Though using `anthropic/claude-3-5-sonnet-20240620` it can't find the MAX_TOKENS. I used `anthropic/claude-3-opus-20240229` for now. 

Full command that works: 
```
docker run --platform linux/amd64 --rm -it 
-e config.model="anthropic/claude-3-opus-20240229" 
-e config.model_turbo="anthropic/claude-3-opus-20240229" 
-e config.fallback_models="anthropic/claude-3-opus-20240229" 
-e ANTHROPIC.KEY=... 
-e GITHUB.USER_TOKEN=...
codiumai/pr-agent --pr_url "$pr_url" "$review_command" 
--pr_description.keep_original_user_title=true 
--pr_code_suggestions.commitable_code_suggestions=true

```

**Comment by mrT23** [comment]
https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/algo/__init__.py#L56

also:
https://qodo-merge-docs.qodo.ai/usage-guide/changing_a_model/#custom-models
