### ISSUE TITLE
When I run CI/CD, there is a error : Error during LLM inference: litellm.APIConnectionError: APIConnectionError: OpenAIException - can't start new thread

### ISSUE THREAD

**Issue by zhangjiuyang1993** [Codium-ai/pr-agent#1324]
2024-10-31 05:42:11.835 | WARNING  | pr_agent.algo.pr_processing:retry_with_fallback_models:348 - Failed to generate prediction with gpt-4o-mini
2024-10-31 05:42:11.835 | ERROR    | pr_agent.tools.pr_description:run:170 - Error generating PR description http://gitlab.ops.haochezhu.club/datascience/lark-notify/-/merge_requests/2: Failed to generate prediction with any model of ['gpt-4o-mini-2024-07-18', 'gpt-4o-mini-2024-07-18', 'gpt-4o-mini']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/pr_agent/cli.py", line 94, in <module>
    run()
  File "/app/pr_agent/cli.py", line 88, in run
    result = asyncio.run(inner())
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 193, in run
    with Runner(debug=debug, loop_factory=loop_factory) as runner:
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 62, in __exit__
    self.close()
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 72, in close
    loop.run_until_complete(
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 598, in shutdown_default_executor
    thread.start()
  File "/usr/local/lib/python3.12/threading.py", line 992, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by zhangjiuyang1993** [comment]
Is my OPENAI_KEY expired?
