### ISSUE TITLE
Running on Local using GROQ key

### ISSUE THREAD

**Issue by mnv1607** [Codium-ai/pr-agent#1344]
when using this model on Local with GROQ key , i am getting an error but in litellm it has given a condtion that if i use any key it will run  when i am using open ai key it is running successfully. The error i am getting is as follows
2024-11-05 16:28:06.207 | INFO     | pr_agent.git_providers.git_provider:get_main_pr_language:266 - No languages detected
2024-11-05 16:28:06.588 | INFO     | pr_agent.tools.pr_reviewer:run:111 - Reviewing PR: https://github.com/kashimnv/consolidate/pull/1 ...
2024-11-05 16:28:12.835 | INFO     | pr_agent.algo.pr_processing:get_pr_diff:63 - PR main language: Other
2024-11-05 16:28:12.843 | INFO     | pr_agent.algo.pr_processing:get_pr_diff:74 - Tokens: 1740, total tokens under limit: 32000, returning full diff.

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-05 16:28:14.337 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-05 16:28:14.941 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-05 16:28:15.825 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-05 16:28:16.990 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-05 16:28:17.346 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 
2024-11-05 16:28:17.356 | WARNING  | pr_agent.algo.pr_processing:retry_with_fallback_models:331 - Failed to generate prediction with gpt-4-turbo-2024-04-09: Traceback (most recent call last):
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\main.py", line 401, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\llms\openai.py", line 1124, in acompletion
    raise e
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\llms\openai.py", line 1079, in acompletion
    headers, response = await self.make_openai_chat_completion_request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\llms\openai.py", line 781, in make_openai_chat_completion_request   
    raise e
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\llms\openai.py", line 772, in make_openai_chat_completion_request   
    await openai_aclient.chat.completions.with_raw_response.create(
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\openai\_legacy_response.py", line 367, in wrapped
    return cast(LegacyAPIResponse[R], await func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\openai\resources\chat\completions.py", line 1339, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\openai\_base_client.py", line 1815, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\openai\_base_client.py", line 1509, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\openai\_base_client.py", line 1610, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: gsk_gWGM********************************************nJwK. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\pr_agent\algo\ai_handlers\litellm_ai_handler.py", line 216, in chat_completion
    response = await acompletion(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\utils.py", line 1579, in wrapper_async
    raise e
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\utils.py", line 1399, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\main.py", line 424, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\utils.py", line 8301, in exception_type
    raise e
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\utils.py", line 6651, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: litellm.AuthenticationError: AuthenticationError: OpenAIException - Incorrect API key provided: gsk_gWGM********************************************nJwK. You can find your API key at https://platform.openai.com/account/api-keys.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\pr_agent\algo\pr_processing.py", line 329, in retry_with_fallback_models    
    return await f(model)
           ^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\pr_agent\tools\pr_reviewer.py", line 163, in _prepare_prediction
    self.prediction = await self._get_prediction(model)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\pr_agent\tools\pr_reviewer.py", line 185, in _get_prediction
    response, finish_reason = await self.ai_handler.chat_completion(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1393d4fcd10 state=finished raised AuthenticationError>]

2024-11-05 16:28:17.676 | INFO     | pr_agent.algo.pr_processing:get_pr_diff:63 - PR main language: Other
2024-11-05 16:28:17.681 | INFO     | pr_agent.algo.pr_processing:get_pr_diff:74 - Tokens: 1740, total tokens under limit: 32000, returning full diff.

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-05 16:28:18.049 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-05 16:28:18.421 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-05 16:28:18.765 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-05 16:28:23.676 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-05 16:28:24.006 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 
2024-11-05 16:28:24.016 | WARNING  | pr_agent.algo.pr_processing:retry_with_fallback_models:331 - Failed to generate prediction with gpt-4o-2024-05-13: Traceback (most recent call last):
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\main.py", line 401, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\llms\openai.py", line 1124, in acompletion
    raise e
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\llms\openai.py", line 1079, in acompletion
    headers, response = await self.make_openai_chat_completion_request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\llms\openai.py", line 781, in make_openai_chat_completion_request   
    raise e
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\llms\openai.py", line 772, in make_openai_chat_completion_request   
    await openai_aclient.chat.completions.with_raw_response.create(
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\openai\_legacy_response.py", line 367, in wrapped
    return cast(LegacyAPIResponse[R], await func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\openai\resources\chat\completions.py", line 1339, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\openai\_base_client.py", line 1815, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\openai\_base_client.py", line 1509, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\openai\_base_client.py", line 1610, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: gsk_gWGM********************************************nJwK. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\pr_agent\algo\ai_handlers\litellm_ai_handler.py", line 216, in chat_completion
    response = await acompletion(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\utils.py", line 1579, in wrapper_async
    raise e
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\utils.py", line 1399, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\main.py", line 424, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\utils.py", line 8301, in exception_type
    raise e
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\litellm\utils.py", line 6651, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: litellm.AuthenticationError: AuthenticationError: OpenAIException - Incorrect API key provided: gsk_gWGM********************************************nJwK. You can find your API key at https://platform.openai.com/account/api-keys.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\pr_agent\algo\pr_processing.py", line 329, in retry_with_fallback_models    
    return await f(model)
           ^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\pr_agent\tools\pr_reviewer.py", line 163, in _prepare_prediction
    self.prediction = await self._get_prediction(model)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\pr_agent\tools\pr_reviewer.py", line 185, in _get_prediction
    response, finish_reason = await self.ai_handler.chat_completion(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent-1\venv\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1393ca5dc10 state=finished raised AuthenticationError>]

2024-11-05 16:28:24.024 | ERROR    | pr_agent.tools.pr_reviewer:run:152 - Failed to review PR: RetryError[<Future at 0x1393ca5dc10 state=finished raised AuthenticationError>]

**Comment by mrT23** [comment]
follow these instructions closely:
https://qodo-merge-docs.qodo.ai/usage-guide/changing_a_model/#changing-a-model

You must do a proper setup for a local model to get it to work

**Comment by mnv1607** [comment]
i have made the changes in the Config.toml and _secret.toml too but it is still showing me the error for GPT - 4- O. Please suggest me away so that is can be handled by the GROQ kwy . The error is as follows:
2024-11-06 15:27:58.530 | INFO     | pr_agent.git_providers.git_provider:get_main_pr_language:266 - No languages detected
2024-11-06 15:27:58.909 | INFO     | pr_agent.tools.pr_reviewer:run:111 - Reviewing PR: https://github.com/mnv1607/qodo/pull/1 ...
2024-11-06 15:28:00.445 | INFO     | pr_agent.algo.pr_processing:get_pr_diff:63 - PR main language: Other
2024-11-06 15:28:00.448 | INFO     | pr_agent.algo.pr_processing:get_pr_diff:74 - Tokens: 1477, total tokens under limit: 32000, returning full diff.    

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-06 15:28:01.299 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-06 15:28:01.570 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-06 15:28:01.841 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-06 15:28:02.124 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-06 15:28:02.423 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 
2024-11-06 15:28:02.432 | WARNING  | pr_agent.algo.pr_processing:retry_with_fallback_models:331 - Failed to generate prediction with gpt-4-turbo-2024-04-09: Traceback (most recent call last):
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\main.py", line 401, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\llms\openai.py", line 1124, in acompletion
    raise e
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\llms\openai.py", line 1079, in acompletion
    headers, response = await self.make_openai_chat_completion_request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\llms\openai.py", line 781, in make_openai_chat_completion_request
    raise e
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\llms\openai.py", line 772, in make_openai_chat_completion_request
    await openai_aclient.chat.completions.with_raw_response.create(
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\openai\_legacy_response.py", line 367, in wrapped
    return cast(LegacyAPIResponse[R], await func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\openai\resources\chat\completions.py", line 1339, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\openai\_base_client.py", line 1815, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\openai\_base_client.py", line 1509, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\openai\_base_client.py", line 1610, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: gsk_6PhD********************************************H9cb. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\pr_agent\algo\ai_handlers\litellm_ai_handler.py", line 216, in chat_completion
    response = await acompletion(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\utils.py", line 1579, in wrapper_async
    raise e
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\utils.py", line 1399, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\main.py", line 424, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\utils.py", line 8301, in exception_type
    raise e
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\utils.py", line 6651, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: litellm.AuthenticationError: AuthenticationError: OpenAIException - Incorrect API key provided: gsk_6PhD********************************************H9cb. You can find your API key at https://platform.openai.com/account/api-keys.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\pr_agent\algo\pr_processing.py", line 329, in retry_with_fallback_models
    return await f(model)
           ^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\pr_agent\tools\pr_reviewer.py", line 163, in _prepare_prediction
    self.prediction = await self._get_prediction(model)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\pr_agent\tools\pr_reviewer.py", line 185, in _get_prediction
    response, finish_reason = await self.ai_handler.chat_completion(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x14ac56f0350 state=finished raised AuthenticationError>]

2024-11-06 15:28:02.725 | INFO     | pr_agent.algo.pr_processing:get_pr_diff:63 - PR main language: Other
2024-11-06 15:28:02.729 | INFO     | pr_agent.algo.pr_processing:get_pr_diff:74 - Tokens: 1477, total tokens under limit: 32000, returning full diff.    

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-06 15:28:03.024 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-06 15:28:03.305 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-06 15:28:03.609 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-06 15:28:03.878 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-11-06 15:28:04.151 | WARNING  | pr_agent.algo.ai_handlers.litellm_ai_handler:chat_completion:218 - Error during OpenAI inference: 
2024-11-06 15:28:04.155 | WARNING  | pr_agent.algo.pr_processing:retry_with_fallback_models:331 - Failed to generate prediction with gpt-4o-2024-05-13: Traceback (most recent call last):
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\main.py", line 401, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\llms\openai.py", line 1124, in acompletion
    raise e
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\llms\openai.py", line 1079, in acompletion
    headers, response = await self.make_openai_chat_completion_request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\llms\openai.py", line 781, in make_openai_chat_completion_request
    raise e
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\llms\openai.py", line 772, in make_openai_chat_completion_request
    await openai_aclient.chat.completions.with_raw_response.create(
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\openai\_legacy_response.py", line 367, in wrapped
    return cast(LegacyAPIResponse[R], await func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\openai\resources\chat\completions.py", line 1339, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\openai\_base_client.py", line 1815, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\openai\_base_client.py", line 1509, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\openai\_base_client.py", line 1610, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: gsk_6PhD********************************************H9cb. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\pr_agent\algo\ai_handlers\litellm_ai_handler.py", line 216, in chat_completion
    response = await acompletion(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\utils.py", line 1579, in wrapper_async
    raise e
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\utils.py", line 1399, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\main.py", line 424, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\utils.py", line 8301, in exception_type
    raise e
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\litellm\utils.py", line 6651, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: litellm.AuthenticationError: AuthenticationError: OpenAIException - Incorrect API key provided: gsk_6PhD********************************************H9cb. You can find your API key at https://platform.openai.com/account/api-keys.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\pr_agent\algo\pr_processing.py", line 329, in retry_with_fallback_models
    return await f(model)
           ^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\pr_agent\tools\pr_reviewer.py", line 163, in _prepare_prediction
    self.prediction = await self._get_prediction(model)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\pr_agent\tools\pr_reviewer.py", line 185, in _get_prediction
    response, finish_reason = await self.ai_handler.chat_completion(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kashi\pr-agent\venv\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x14ac571dc10 state=finished raised AuthenticationError>]

2024-11-06 15:28:04.165 | ERROR    | pr_agent.tools.pr_reviewer:run:152 - Failed to review PR: RetryError[<Future at 0x14ac571dc10 state=finished raised AuthenticationError>]

**Comment by mrT23** [comment]
what is 'Config.toml' ? where did you see instructions to edit it ? 

you are not following the instructions. do that

**Comment by mnv1607** [comment]
configuration.toml and .secrets_template.toml file in the instructions it has been said to change it and since i am using  a GROQ key i need to make changes in both these files as well

**Comment by mrT23** [comment]
ok. all the best
