### ISSUE TITLE
Gitlab sub groups produce 404 error

### ISSUE THREAD

**Issue by anton-cm** [Codium-ai/pr-agent#135]
When I try to run any review/description/etc on merge request for repo that is in sub group, I get GitlabGetError - 404.

This works
```
https://gitlab.com/org_name/repo_name/-/merge_requests/1 
```
This does not work
(gitlab.exceptions.GitlabGetError: 404: 404 Project Not Found)
Full trace bellow
```
https://gitlab.com/org_name/repos_group/repo_name/-/merge_requests/1 
```

Expected result
```
https://gitlab.com/org_name/repos_group/repo_name/-/merge_requests/1 - should work
```

Full error trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gitlab/exceptions.py", line 336, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gitlab/mixins.py", line 122, in get
    server_data = self.gitlab.http_get(path, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gitlab/client.py", line 828, in http_get
    result = self.http_request(
  File "/usr/local/lib/python3.10/site-packages/gitlab/client.py", line 794, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 404: 404 Project Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/pr_agent/cli.py", line 101, in <module>
    run()
  File "/app/pr_agent/cli.py", line 55, in run
    commands[command](args.pr_url, args.rest)
  File "/app/pr_agent/cli.py", line 84, in _handle_review_command
    reviewer = PRReviewer(pr_url, cli_mode=True, args=rest)
  File "/app/pr_agent/tools/pr_reviewer.py", line 22, in __init__
    self.git_provider = get_git_provider()(pr_url, incremental=self.incremental)
  File "/app/pr_agent/git_providers/gitlab_provider.py", line 34, in __init__
    self._set_merge_request(merge_request_url)
  File "/app/pr_agent/git_providers/gitlab_provider.py", line 51, in _set_merge_request
    self.mr = self._get_merge_request()
  File "/app/pr_agent/git_providers/gitlab_provider.py", line 257, in _get_merge_request
    mr = self.gl.projects.get(self.id_project).mergerequests.get(self.id_mr)
  File "/usr/local/lib/python3.10/site-packages/gitlab/v4/objects/projects.py", line 860, in get
    return cast(Project, super().get(id=id, lazy=lazy, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/gitlab/exceptions.py", line 338, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabGetError: 404: 404 Project Not Found
```

**Comment by anton-cm** [comment]
So basically problem is here:

gitlab_provider.py
_parse_merge_request_url

```
L: 254 
return "/".join(path_parts[:2]), mr_id
```

There could be more than 2 parts here

Can you please fix that?

**Comment by okotek** [comment]
This should solve it https://github.com/Codium-ai/pr-agent/pull/136

**Comment by okotek** [comment]
Merged into main
