### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml' (fixed) 

### ISSUE THREAD

**Issue by Mindgames** [Codium-ai/pr-agent#189]
Running into following issue 

```
Run Codium-ai/pr-agent@main
/usr/bin/docker run --name bedb4853746a2bef44f7888dad2cd8a27189f_7b7377 --label 5bedb4 --workdir /github/workspace --rm -e "OPENAI_KEY" -e "GITHUB_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_DEBUG" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/A1_core/A1_core":"/github/workspace" 5bedb4:853746a2bef44f7888dad2cd8a27189f
Traceback (most recent call last):
  File "/app/pr_agent/servers/github_action_runner.py", line 5, in <module>
    from pr_agent.agent.pr_agent import PRAgent
  File "/app/pr_agent/agent/pr_agent.py", line 6, in <module>
    from pr_agent.algo.utils import update_settings_from_args
  File "/app/pr_agent/algo/utils.py", line 11, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```
Using 
```
on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by mrkmcknz** [comment]
Same here.

```
Traceback (most recent call last):
  File "/app/pr_agent/servers/github_action_runner.py", line 5, in <module>
    from pr_agent.agent.pr_agent import PRAgent
  File "/app/pr_agent/agent/pr_agent.py", line 6, in <module>
    from pr_agent.algo.utils import update_settings_from_args
  File "/app/pr_agent/algo/utils.py", line [11](https://github.com/Apollo-xyz/apollo-api/actions/runs/5814083083/job/15763034821?pr=319#step:3:12), in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by coditamar** [comment]
Can you please add PyYAML to the requirements.txt and see if it works for you?

**Comment by chl03ks** [comment]
same here, how can we fix this if we are using the github action ?

**Comment by okotek** [comment]
Fixed.
