### ISSUE TITLE
Error sending sign-in link: Firebase: Error (auth/network-request-failed)

### ISSUE THREAD

**Issue by 271374667** [Codium-ai/pr-agent#243]
I can't log in to codium, whether I use github, google or email. If I use vpn, I can log in on the web page, but I still can't make pycharm or vscode work normally. On pycharm, my request will be

Request ID:9fe62808-782b-48a3-91ab-1b70837d0a17

- I have turned off my firewall
- My system version is window 10 professional 64 bit 22H2
- pycharm 2023.2
- vscode insider 1.79.0

The following is the error from pycharm

```
Failed to execute 'https://identitytoolkit.googleapis.com/v1/accounts:signInWithIdp' network request (attempt 3/3): Failed to connect 
to identitytoolkit.googleapis.com/142.251.42.234:443 java.net.ConnectException: Failed to connect to 
identitytoolkit.googleapis.com/142.251.42.234:443 at 
okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297) at 
okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207) at 
okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226) at 
okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) at 
okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) at 
okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) at 
okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) at 
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) at 
okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) at 
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) at 
okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) at 
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) at 
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) at 
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) at 
okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) at 
okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) at retrofit2.OkHttpCall.execute(OkHttpCall.java:204) at 
ai.codium.net.CodiumNetworkClient.executeRequest(CodiumNetworkClient.kt:50) at 
ai.codium.net.CodiumNetworkClient.executeRequest(CodiumNetworkClient.kt:65) at 
ai.codium.net.CodiumNetworkClient.executeRequest(CodiumNetworkClient.kt:65) at 
ai.codium.net.CodiumNetworkClient.executeRequest$default(CodiumNetworkClient.kt:26) at 
ai.codium.net.CodiumFirebaseApiClient.signInWithProvider$codium_ai_plugin(CodiumFirebaseApiClient.kt:20) at 
ai.codium.net.CodiumNetworkService.loginToFirebase(CodiumNetworkService.kt:149) at 
ai.codium.net.CodiumHttpRequestHandler.process(CodiumHttpRequestHandler.kt:68) at 
org.jetbrains.io.DelegatingHttpRequestHandler.process$checkAndProcess(DelegatingHttpRequestHandler.kt:21) at 
org.jetbrains.io.DelegatingHttpRequestHandler.access$process$checkAndProcess(DelegatingHttpRequestHandler.kt:15) at 
org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:35) at 
org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:34) at 
org.jetbrains.io.DelegatingHttpRequestHandler.process$lambda$0(DelegatingHttpRequestHandler.kt:34) at 
com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.findFirstSafe$lambda$0(ExtensionProcessingHelper.kt:47) at 
com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.kt:57) at 
com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.findFirstSafe(ExtensionProcessingHelper.kt:47) at 
com.intellij.openapi.extensions.ExtensionPointName.findFirstSafe(ExtensionPointName.kt:53) at 
org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.kt:34) at 
org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:15) at 
org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:11) at 
org.jetbrains.io.SimpleChannelInboundHandlerAdapter.channelRead0(SimpleChannelInboundHandlerAdapter.java:21) at 
io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) at 
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) at 
io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:95) at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) at 
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) at 
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) at 
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) at 
io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) at 
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) at 
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) at 
org.jetbrains.io.PortUnificationServerHandler.decode(PortUnificationServerHandler.java:129) at 
org.jetbrains.io.PortUnificationServerHandler.messageReceived(PortUnificationServerHandler.java:77) at 
org.jetbrains.io.Decoder.channelRead(Decoder.java:23) at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) at 
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) at 
io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) at 
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) at 
io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) at 
io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) at 
io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) at 
io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) at 
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) at 
io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) at 
io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at 
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at 
java.base/java.lang.Thread.run(Thread.java:833) Suppressed: java.net.ConnectException: Failed to connect to 
identitytoolkit.googleapis.com/172.217.160.106:443 ... 73 more Caused by: java.net.ConnectException: Connection timed out: no 
further information at java.base/sun.nio.ch.Net.pollConnect(Native Method) at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672) 
at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) at 
java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) at 
java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) at java.base/java.net.Socket.connect(Socket.java:633) at 
okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128) at 
okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295) ... 72 more Suppressed: java.net.ConnectException:
 Failed to connect to identitytoolkit.googleapis.com/142.251.43.10:443 ... 73 more Caused by: java.net.ConnectException: Connection 
timed out: no further information at java.base/sun.nio.ch.Net.pollConnect(Native Method) at 
java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672) at 
java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) at 
java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) at 
java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) at java.base/java.net.Socket.connect(Socket.java:633) at 
okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128) at 
okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295) ... 72 more Caused by: java.net.ConnectException: 
Connection timed out: no further information at java.base/sun.nio.ch.Net.pollConnect(Native Method) at 
java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672) at 
java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) at 
java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) at 
java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) at java.base/java.net.Socket.connect(Socket.java:633) at 
okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128) at 
okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295) ... 72 more
```

**Comment by mrT23** [comment]
hi @271374667 

Please open this issue in the discord of Codium (IDE extension):
https://discord.com/channels/1057273017547378788/1075012292854435840

PR-Agent is a separate product
