### ISSUE TITLE
[BUG] Problem with /improve and /impove --extended

### ISSUE THREAD

**Issue by MindsightsAI** [Codium-ai/pr-agent#313]
Full log:

```
WARNING:root:Failed to generate prediction with gpt-4: Traceback (most recent call last):
  File "/app/pr_agent/algo/git_patch_processing.py", line 211, in convert_to_hunks_with_lines_numbers
    start1, size1, start2, size2 = map(int, match.groups()[:4])
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/pr_agent/algo/pr_processing.py", line 215, in retry_with_fallback_models
    return await f(model)
  File "/app/pr_agent/tools/pr_code_suggestions.py", line 75, in _prepare_prediction
    self.patches_diff = get_pr_diff(self.git_provider,
  File "/app/pr_agent/algo/pr_processing.py", line 60, in get_pr_diff
    patches_extended, total_tokens, patches_extended_tokens = pr_generate_extended_diff(pr_languages, token_handler,
  File "/app/pr_agent/algo/pr_processing.py", line 109, in pr_generate_extended_diff
    full_extended_patch = convert_to_hunks_with_lines_numbers(extended_patch, file)
  File "/app/pr_agent/algo/git_patch_processing.py", line 213, in convert_to_hunks_with_lines_numbers
    start1, size1, size2 = map(int, match.groups()[:3])
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

INFO:root:Getting PR diff...
WARNING:root:Failed to generate prediction with gpt-3.5-turbo-16k: Traceback (most recent call last):
  File "/app/pr_agent/algo/git_patch_processing.py", line 211, in convert_to_hunks_with_lines_numbers
    start1, size1, start2, size2 = map(int, match.groups()[:4])
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/pr_agent/algo/pr_processing.py", line 215, in retry_with_fallback_models
    return await f(model)
  File "/app/pr_agent/tools/pr_code_suggestions.py", line 75, in _prepare_prediction
    self.patches_diff = get_pr_diff(self.git_provider,
  File "/app/pr_agent/algo/pr_processing.py", line 60, in get_pr_diff
    patches_extended, total_tokens, patches_extended_tokens = pr_generate_extended_diff(pr_languages, token_handler,
  File "/app/pr_agent/algo/pr_processing.py", line 109, in pr_generate_extended_diff
    full_extended_patch = convert_to_hunks_with_lines_numbers(extended_patch, file)
  File "/app/pr_agent/algo/git_patch_processing.py", line 213, in convert_to_hunks_with_lines_numbers
    start1, size1, size2 = map(int, match.groups()[:3])
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

Traceback (most recent call last):
  File "/app/pr_agent/algo/git_patch_processing.py", line 211, in convert_to_hunks_with_lines_numbers
    start1, size1, start2, size2 = map(int, match.groups()[:4])
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/pr_agent/servers/github_action_runner.py", line 120, in <module>
    asyncio.run(run_action())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/pr_agent/servers/github_action_runner.py", line 94, in run_action
    await PRAgent().handle_request(pr_url, new_command)
  File "/app/pr_agent/agent/pr_agent.py", line 82, in handle_request
    await command2class[action](pr_url, args=args).run()
  File "/app/pr_agent/tools/pr_code_suggestions.py", line 57, in run
    await retry_with_fallback_models(self._prepare_prediction)
  File "/app/pr_agent/algo/pr_processing.py", line 215, in retry_with_fallback_models
    return await f(model)
  File "/app/pr_agent/tools/pr_code_suggestions.py", line 75, in _prepare_prediction
    self.patches_diff = get_pr_diff(self.git_provider,
  File "/app/pr_agent/algo/pr_processing.py", line 60, in get_pr_diff
    patches_extended, total_tokens, patches_extended_tokens = pr_generate_extended_diff(pr_languages, token_handler,
  File "/app/pr_agent/algo/pr_processing.py", line 109, in pr_generate_extended_diff
    full_extended_patch = convert_to_hunks_with_lines_numbers(extended_patch, file)
  File "/app/pr_agent/algo/git_patch_processing.py", line 213, in convert_to_hunks_with_lines_numbers
    start1, size1, size2 = map(int, match.groups()[:3])
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by mrT23** [comment]
can you share a reproducable example ?

**Comment by MindsightsAI** [comment]
Yep, here is [demo repository](https://github.com/Inside-AI-me/demo-repository) with github [action](https://github.com/Inside-AI-me/pr-agent/blob/main/.github/workflows/inside-package.yaml). It use pr-agent form github package. [PR-agent fork](https://github.com/Inside-AI-me/pr-agent) with pr_commands and local config reader applied to github_action_runner and published to github package. I've added you to both repositories.

**Comment by mrT23** [comment]
i think this should fix this, some patch formatting issues

https://github.com/Codium-ai/pr-agent/pull/315

![image](https://github.com/Codium-ai/pr-agent/assets/21198860/1eb8695a-049c-43cb-bbd3-334592591906)
