### ISSUE TITLE
[GITLAB] describe command failing

### ISSUE THREAD

**Issue by pushpanktugnawat** [Codium-ai/pr-agent#319]
Hey Team,

While generating the description in GitLab it fails for the following reasons. Could you please check and help me to handle it?

`
Status: Downloaded newer image for codiumai/pr-agent:latest
Traceback (most recent call last):
  File "/app/pr_agent/cli.py", line 62, in <module>
    run()
  File "/app/pr_agent/cli.py", line 56, in run
    result = asyncio.run(PRAgent().handle_request(args.pr_url, command + " " + " ".join(args.rest)))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/pr_agent/agent/pr_agent.py", line 81, in handle_request
    await command2class[action](pr_url, args=args).run()
  File "/app/pr_agent/tools/pr_description.py", line 32, in __init__
    self.pr_id = f"{self.git_provider.repo}/{self.git_provider.pr_num}"
AttributeError: 'GitLabProvider' object has no attribute 'repo'
Cleaning up project directory and file based variables
`

**Comment by pushpanktugnawat** [comment]
Please treat it as blocker if possible.

**Comment by mrT23** [comment]
Sorry for this.

https://github.com/Codium-ai/pr-agent/pull/320 should fix.
Let me know if the issue persists
