### ISSUE TITLE
/improve timeout problem

### ISSUE THREAD

**Issue by MindsightsAI** [Codium-ai/pr-agent#323]
Logs:
```
[pr-agent] [2023-09-22 15:36:19] INFO:     140.82.115.25:0 - "POST /api/v1/github_webhooks HTTP/1.1" 200 OK
[pr-agent] [2023-09-22 15:38:59] --- Logging error ---
[pr-agent] [2023-09-22 15:38:59] Traceback (most recent call last):
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/litellm/timeout.py", line 44, in wrapper
[pr-agent] [2023-09-22 15:38:59]     result = future.result(timeout=local_timeout_duration)
[pr-agent] [2023-09-22 15:38:59]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/concurrent/futures/_base.py", line 458, in result
[pr-agent] [2023-09-22 15:38:59]     raise TimeoutError()
[pr-agent] [2023-09-22 15:38:59] TimeoutError
[pr-agent] [2023-09-22 15:38:59] 
[pr-agent] [2023-09-22 15:38:59] During handling of the above exception, another exception occurred:
[pr-agent] [2023-09-22 15:38:59] 
[pr-agent] [2023-09-22 15:38:59] Traceback (most recent call last):
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/pr_agent/algo/ai_handler.py", line 95, in chat_completion
[pr-agent] [2023-09-22 15:38:59]     response = await acompletion(
[pr-agent] [2023-09-22 15:38:59]                ^^^^^^^^^^^^^^^^^^
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/litellm/main.py", line 85, in acompletion
[pr-agent] [2023-09-22 15:38:59]     response =  await loop.run_in_executor(None, func_with_context)
[pr-agent] [2023-09-22 15:38:59]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/concurrent/futures/thread.py", line 58, in run
[pr-agent] [2023-09-22 15:38:59]     result = self.fn(*self.args, **self.kwargs)
[pr-agent] [2023-09-22 15:38:59]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/litellm/utils.py", line 651, in wrapper
[pr-agent] [2023-09-22 15:38:59]     raise e
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/litellm/utils.py", line 610, in wrapper
[pr-agent] [2023-09-22 15:38:59]     result = original_function(*args, **kwargs)
[pr-agent] [2023-09-22 15:38:59]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/litellm/timeout.py", line 47, in wrapper
[pr-agent] [2023-09-22 15:38:59]     raise exception_to_raise(
[pr-agent] [2023-09-22 15:38:59] openai.error.Timeout: A timeout error occurred. The function call took longer than 180 second(s).
[pr-agent] [2023-09-22 15:38:59] 
[pr-agent] [2023-09-22 15:38:59] During handling of the above exception, another exception occurred:
[pr-agent] [2023-09-22 15:38:59] 
[pr-agent] [2023-09-22 15:38:59] Traceback (most recent call last):
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/logging/__init__.py", line 1110, in emit
[pr-agent] [2023-09-22 15:38:59]     msg = self.format(record)
[pr-agent] [2023-09-22 15:38:59]           ^^^^^^^^^^^^^^^^^^^
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/logging/__init__.py", line 953, in format
[pr-agent] [2023-09-22 15:38:59]     return fmt.format(record)
[pr-agent] [2023-09-22 15:38:59]            ^^^^^^^^^^^^^^^^^^
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/logging/__init__.py", line 687, in format
[pr-agent] [2023-09-22 15:38:59]     record.message = record.getMessage()
[pr-agent] [2023-09-22 15:38:59]                      ^^^^^^^^^^^^^^^^^^^
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/logging/__init__.py", line 377, in getMessage
[pr-agent] [2023-09-22 15:38:59]     msg = msg % self.args
[pr-agent] [2023-09-22 15:38:59]           ~~~~^~~~~~~~~~~
[pr-agent] [2023-09-22 15:38:59] TypeError: not all arguments converted during string formatting
[pr-agent] [2023-09-22 15:38:59] Call stack:
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/pr_agent/servers/github_app.py", line 229, in <module>
[pr-agent] [2023-09-22 15:38:59]     start()
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/pr_agent/servers/github_app.py", line 225, in start
[pr-agent] [2023-09-22 15:38:59]     uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("PORT", "3000")))
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/uvicorn/main.py", line 578, in run
[pr-agent] [2023-09-22 15:38:59]     server.run()
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
[pr-agent] [2023-09-22 15:38:59]     return asyncio.run(self.serve(sockets=sockets))
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/asyncio/runners.py", line 190, in run
[pr-agent] [2023-09-22 15:38:59]     return runner.run(main)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/asyncio/runners.py", line 118, in run
[pr-agent] [2023-09-22 15:38:59]     return self._loop.run_until_complete(task)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
[pr-agent] [2023-09-22 15:38:59]     self.run_forever()
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
[pr-agent] [2023-09-22 15:38:59]     self._run_once()
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
[pr-agent] [2023-09-22 15:38:59]     handle._run()
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/asyncio/events.py", line 80, in _run
[pr-agent] [2023-09-22 15:38:59]     self._context.run(self._callback, *self._args)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
[pr-agent] [2023-09-22 15:38:59]     result = await app(  # type: ignore[func-returns-value]
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
[pr-agent] [2023-09-22 15:38:59]     return await self.app(scope, receive, send)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/fastapi/applications.py", line 290, in __call__
[pr-agent] [2023-09-22 15:38:59]     await super().__call__(scope, receive, send)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
[pr-agent] [2023-09-22 15:38:59]     await self.middleware_stack(scope, receive, send)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
[pr-agent] [2023-09-22 15:38:59]     await self.app(scope, receive, _send)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/starlette_context/middleware/raw_middleware.py", line 92, in __call__
[pr-agent] [2023-09-22 15:38:59]     await self.app(scope, receive, send_wrapper)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
[pr-agent] [2023-09-22 15:38:59]     await self.app(scope, receive, sender)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
[pr-agent] [2023-09-22 15:38:59]     await self.app(scope, receive, send)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
[pr-agent] [2023-09-22 15:38:59]     await route.handle(scope, receive, send)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
[pr-agent] [2023-09-22 15:38:59]     await self.app(scope, receive, send)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
[pr-agent] [2023-09-22 15:38:59]     response = await func(request)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
[pr-agent] [2023-09-22 15:38:59]     raw_response = await run_endpoint_function(
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
[pr-agent] [2023-09-22 15:38:59]     return await dependant.call(**values)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/pr_agent/servers/github_app.py", line 64, in handle_github_webhooks
[pr-agent] [2023-09-22 15:38:59]     response = await handle_request(body, event=request.headers.get("X-GitHub-Event", None))
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/pr_agent/servers/github_app.py", line 129, in handle_request
[pr-agent] [2023-09-22 15:38:59]     await agent.handle_request(api_url, comment_body, notify=lambda: provider.add_eyes_reaction(comment_id))
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/pr_agent/agent/pr_agent.py", line 82, in handle_request
[pr-agent] [2023-09-22 15:38:59]     await command2class[action](pr_url, args=args).run()
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/pr_agent/tools/pr_code_suggestions.py", line 58, in run
[pr-agent] [2023-09-22 15:38:59]     await retry_with_fallback_models(self._prepare_prediction)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/pr_agent/algo/pr_processing.py", line 215, in retry_with_fallback_models
[pr-agent] [2023-09-22 15:38:59]     return await f(model)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/pr_agent/tools/pr_code_suggestions.py", line 88, in _prepare_prediction
[pr-agent] [2023-09-22 15:38:59]     self.prediction = await self._get_prediction(model)
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/pr_agent/tools/pr_code_suggestions.py", line 99, in _get_prediction
[pr-agent] [2023-09-22 15:38:59]     response, finish_reason = await self.ai_handler.chat_completion(model=model, temperature=0.2,
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/pr_agent/algo/ai_handler.py", line 107, in chat_completion
[pr-agent] [2023-09-22 15:38:59]     logging.error("Error during OpenAI inference: ", e)
[pr-agent] [2023-09-22 15:38:59] Message: 'Error during OpenAI inference: '
[pr-agent] [2023-09-22 15:38:59] Arguments: (Timeout(message='A timeout error occurred. The function call took longer than 180 second(s).', http_status=None, request_id=None),)
[pr-agent] [2023-09-22 15:38:59] WARNING:root:Failed to generate prediction with gpt-4: Traceback (most recent call last):
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/litellm/timeout.py", line 44, in wrapper
[pr-agent] [2023-09-22 15:38:59]     result = future.result(timeout=local_timeout_duration)
[pr-agent] [2023-09-22 15:38:59]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/concurrent/futures/_base.py", line 458, in result
[pr-agent] [2023-09-22 15:38:59]     raise TimeoutError()
[pr-agent] [2023-09-22 15:38:59] TimeoutError
[pr-agent] [2023-09-22 15:38:59] 
[pr-agent] [2023-09-22 15:38:59] During handling of the above exception, another exception occurred:
[pr-agent] [2023-09-22 15:38:59] 
[pr-agent] [2023-09-22 15:38:59] Traceback (most recent call last):
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/pr_agent/algo/pr_processing.py", line 215, in retry_with_fallback_models
[pr-agent] [2023-09-22 15:38:59]     return await f(model)
[pr-agent] [2023-09-22 15:38:59]            ^^^^^^^^^^^^^^
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/pr_agent/tools/pr_code_suggestions.py", line 88, in _prepare_prediction
[pr-agent] [2023-09-22 15:38:59]     self.prediction = await self._get_prediction(model)
[pr-agent] [2023-09-22 15:38:59]                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/pr_agent/tools/pr_code_suggestions.py", line 99, in _get_prediction
[pr-agent] [2023-09-22 15:38:59]     response, finish_reason = await self.ai_handler.chat_completion(model=model, temperature=0.2,
[pr-agent] [2023-09-22 15:38:59]                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/pr_agent/algo/ai_handler.py", line 95, in chat_completion
[pr-agent] [2023-09-22 15:38:59]     response = await acompletion(
[pr-agent] [2023-09-22 15:38:59]                ^^^^^^^^^^^^^^^^^^
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/litellm/main.py", line 85, in acompletion
[pr-agent] [2023-09-22 15:38:59]     response =  await loop.run_in_executor(None, func_with_context)
[pr-agent] [2023-09-22 15:38:59]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/concurrent/futures/thread.py", line 58, in run
[pr-agent] [2023-09-22 15:38:59]     result = self.fn(*self.args, **self.kwargs)
[pr-agent] [2023-09-22 15:38:59]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/litellm/utils.py", line 651, in wrapper
[pr-agent] [2023-09-22 15:38:59]     raise e
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/litellm/utils.py", line 610, in wrapper
[pr-agent] [2023-09-22 15:38:59]     result = original_function(*args, **kwargs)
[pr-agent] [2023-09-22 15:38:59]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pr-agent] [2023-09-22 15:38:59]   File "/workspace/.heroku/python/lib/python3.11/site-packages/litellm/timeout.py", line 47, in wrapper
[pr-agent] [2023-09-22 15:38:59]     raise exception_to_raise(
[pr-agent] [2023-09-22 15:38:59] openai.error.Timeout: A timeout error occurred. The function call took longer than 180 second(s).
[pr-agent] [2023-09-22 15:38:59] 
[pr-agent] [2023-09-22 15:39:00] WARNING:root:Patch too large, minimizing it, src/ui/meet/features/SidePanel/SidePanel.scss
[pr-agent] [2023-09-22 15:39:00] WARNING:root:Patch too large, minimizing it, src/ui/meet/features/SidePanel/components/MessageTabs/MessageTabs.scss
[pr-agent] [2023-09-22 15:39:00] WARNING:root:Patch too large, minimizing it, tsconfig.json
[pr-agent] [2023-09-22 15:39:00] WARNING:root:Patch too large, minimizing it, package.json
[pr-agent] [2023-09-22 15:39:42] Code suggestions:
[pr-agent] [2023-09-22 15:39:42]   - relevant file: |-
[pr-agent] [2023-09-22 15:39:42]       src/ui/meet/features/SidePanel/components/TranscriptsIcon/TranscriptsIcon.tsx
[pr-agent] [2023-09-22 15:39:42]     suggestion content: |-
[pr-agent] [2023-09-22 15:39:42]       Add type annotations to the Props interface in TranscriptsIcon.tsx
[pr-agent] [2023-09-22 15:39:42]     existing code: |-
[pr-agent] [2023-09-22 15:39:42]       type Props = {
[pr-agent] [2023-09-22 15:39:42]         isActive?: boolean;
[pr-agent] [2023-09-22 15:39:42]       };
[pr-agent] [2023-09-22 15:39:42]     relevant lines start: 1
[pr-agent] [2023-09-22 15:39:42]     relevant lines end: 3
[pr-agent] [2023-09-22 15:39:42]     improved code: |-
[pr-agent] [2023-09-22 15:39:42]       type Props = {
[pr-agent] [2023-09-22 15:39:42]         isActive?: boolean;
[pr-agent] [2023-09-22 15:39:42]       } as const;
[pr-agent] [2023-09-22 15:39:42]       
[pr-agent] [2023-09-22 15:39:42]       export const TranscriptsIcon = ({ isActive }: Props) => {
[pr-agent] [2023-09-22 15:39:42]         const fillColor = isActive ? "rgb(138,180,248)" : "#fff";
[pr-agent] [2023-09-22 15:39:42]       
[pr-agent] [2023-09-22 15:39:42]         return (
[pr-agent] [2023-09-22 15:39:42]           <svg fill='none' height='24' viewBox='0 0 22 24' width='24' xmlns='http://www.w3.org/2000/svg'>
[pr-agent] [2023-09-22 15:39:42]             <mask
[pr-agent] [2023-09-22 15:39:42]               height='24'
[pr-agent] [2023-09-22 15:39:42]               id='mask0_1665_555'
[pr-agent] [2023-09-22 15:39:42]               maskUnits='userSpaceOnUse'
[pr-agent] [2023-09-22 15:39:42]               style={{ maskType: "alpha" }}
[pr-agent] [2023-09-22 15:39:42]               width='24'
[pr-agent] [2023-09-22 15:39:42]               x='0'
[pr-agent] [2023-09-22 15:39:42]               y='0'
[pr-agent] [2023-09-22 15:39:42]             >
[pr-agent] [2023-09-22 15:39:42]               <path d='M0 0H24V24H0z' fill='#93B3F2'></path>
[pr-agent] [2023-09-22 15:39:42]             </mask>
[pr-agent] [2023-09-22 15:39:42]             <g mask='url(#mask0_1665_555)'>
[pr-agent] [2023-09-22 15:39:42]               <mask
[pr-agent] [2023-09-22 15:39:42]                 height='24'
[pr-agent] [2023-09-22 15:39:42]                 id='mask1_1665_555'
[pr-agent] [2023-09-22 15:39:42]                 maskUnits='userSpaceOnUse'
[pr-agent] [2023-09-22 15:39:42]                 style={{ maskType: "alpha" }}
[pr-agent] [2023-09-22 15:39:42]                 width='24'
[pr-agent] [2023-09-22 15:39:42]                 x='0'
[pr-agent] [2023-09-22 15:39:42]                 y='0'
[pr-agent] [2023-09-22 15:39:42]               >
[pr-agent] [2023-09-22 15:39:42]                 <path d='M0 0H24V24H0z' fill='#93B3F2'></path>
[pr-agent] [2023-09-22 15:39:42]               </mask>
[pr-agent] [2023-09-22 15:39:42]               <g mask='url(#mask1_1665_555)'>
[pr-agent] [2023-09-22 15:39:42]                 <mask
[pr-agent] [2023-09-22 15:39:42]                   height='24'
[pr-agent] [2023-09-22 15:39:42]                   id='mask2_1665_555'
[pr-agent] [2023-09-22 15:39:42]                   maskUnits='userSpaceOnUse'
[pr-agent] [2023-09-22 15:39:42]                   style={{ maskType: "alpha" }}
[pr-agent] [2023-09-22 15:39:42]                   width='24'
[pr-agent] [2023-09-22 15:39:42]                   x='0'
[pr-agent] [2023-09-22 15:39:42]                   y='0'
[pr-agent] [2023-09-22 15:39:42]                 >
[pr-agent] [2023-09-22 15:39:42]                   <path d='M0 0H24V24H0z' fill='#D9D9D9'></path>
[pr-agent] [2023-09-22 15:39:42]                 </mask>
[pr-agent] [2023-09-22 15:39:42]                 <g fill={fillColor} mask='url(#mask2_1665_555)'>
[pr-agent] [2023-09-22 15:39:42]                   <path d='M9 13c-1.1 0-2.042-.392-2.825-1.175C5.392 11.042 5 10.1 5 9s.392-2.042 1.175-2.825C6.958 5.392 7.9 5 9 5s2.042.392 2.825 1.175C12.608 6.958 13 7.9 13 9s-.392 2.042-1.175 2.825C11.042 12.608 10.1 13 9 13zm-8 8v-2.8c0-.55.142-1.067.425-1.55.283-.483.675-.85 1.175-1.1.85-.433 1.808-.8 2.875-1.1C6.542 14.15 7.717 14 9 14s2.458.15 3.525.45c1.067.3 2.025.667 2.875 1.1.5.25.892.617 1.175 1.1.283.483.425 1 .425 1.55V21H1zm2-2h12v-.8a.973.973 0 00-.5-.85c-.6-.3-1.37-.6-2.313-.9-.941-.3-2.004-.45-3.187-.45-1.183 0-2.246.15-3.188.45-.941.3-1.712.6-2.312.9a.973.973 0 00-.5.85v.8zm6-8c.55 0 1.02-.196 1.413-.587.391-.392.587-.863.587-1.413s-.196-1.02-.587-1.412A1.926 1.926 0 009 7c-.55 0-1.02.196-1.413.588A1.926 1.926 0 007 9c0 .55.196 1.02.587 1.413.392.391.863.587 1.413.587z'></path>
[pr-agent] [2023-09-22 15:39:42]                   <path
[pr-agent] [2023-09-22 15:39:42]                     clipRule='evenodd'
[pr-agent] [2023-09-22 15:39:42]                     d='M14 10V1.9c0-.247.088-.46.264-.636A.867.867 0 0114.9 1h7.2c.247 0 .46.088.636.264A.866.866 0 0123 1.9v5.4c0 .248-.088.46-.264.636a.867.867 0 01-.636.264h-6.3L14 10zm4.5-3l-.781-1.719L16 4.5l1.719-.781L18.5 2l.781 1.719L21 4.5l-1.719.781L18.5 7z'
[pr-agent] [2023-09-22 15:39:42]                     fillRule='evenodd'
[pr-agent] [2023-09-22 15:39:42]                   ></path>
[pr-agent] [2023-09-22 15:39:42]                 </g>
[pr-agent] [2023-09-22 15:39:42]               </g>
[pr-agent] [2023-09-22 15:39:42]             </g>
[pr-agent] [2023-09-22 15:39:42]           </svg>
[pr-agent] [2023-09-22 15:39:42]         );
[pr-agent] [2023-09-22 15:39:42]       };
[pr-agent] [2023-09-22 15:39:42]  stop
[pr-agent] [2023-09-22 15:39:42] ERROR:root:Failed to publish code suggestion, error: 422 {"message": "Unprocessable Entity", "errors": ["Pull request review thread line must be part of the diff, Pull request review thread start line must be part of the same hunk as the line., and Pull request review thread diff hunk can't be blank"], "documentation_url": "https://docs.github.com/rest/pulls/reviews#create-a-review-for-a-pull-request"}
```

**Comment by mrT23** [comment]
seems like an OPENAI issue. It happens

PR-Agent didn't crush, right ? 
If so, this is a reasonable treatment of pr-agent with this kind of issue - output the error message

**Comment by MindsightsAI** [comment]
Yes, the pr-agent continued to work
