### ISSUE TITLE
GitLab: authorization problem

### ISSUE THREAD

**Issue by rliskunov** [Codium-ai/pr-agent#335]
I run with docker command bellow with:

- Self Host GitLab Community Edition 15.11.2
- Private project
- Access Token (scope: api): tried both with group/project and personal access token
- Image codiumai/pr-agent: tried both 0.7 and 0.8 versions

```
docker run --rm -it  \
  -e OPENAI.KEY=$OPENAI_KEY \
  -e CONFIG.GIT_PROVIDER=gitlab  \
  -e GITLAB.PERSONAL_ACCESS_TOKEN=$GITLAB_PAT \
  codiumai/pr-agent:$TAG --pr_url $MR_URL review
```
However, I encountered the following error. 

```
Traceback (most recent call last):
  File "/app/pr_agent/cli.py", line 45, in <module>
    run()
  File "/app/pr_agent/cli.py", line 39, in run
    result = asyncio.run(PRAgent().handle_request(args.pr_url, command + " " + " ".join(args.rest)))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/pr_agent/agent/pr_agent.py", line 45, in handle_request
    git_provider = get_git_provider()(pr_url)
  File "/app/pr_agent/git_providers/gitlab_provider.py", line 37, in __init__
    self._set_merge_request(merge_request_url)
  File "/app/pr_agent/git_providers/gitlab_provider.py", line 54, in _set_merge_request
    self.mr = self._get_merge_request()
  File "/app/pr_agent/git_providers/gitlab_provider.py", line 326, in _get_merge_request
    mr = self.gl.projects.get(self.id_project).mergerequests.get(self.id_mr)
  File "/usr/local/lib/python3.10/site-packages/gitlab/v4/objects/projects.py", line 860, in get
    return cast(Project, super().get(id=id, lazy=lazy, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/gitlab/exceptions.py", line 336, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gitlab/mixins.py", line 122, in get
    server_data = self.gitlab.http_get(path, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gitlab/client.py", line 828, in http_get
    result = self.http_request(
  File "/usr/local/lib/python3.10/site-packages/gitlab/client.py", line 788, in http_request
    raise gitlab.exceptions.GitlabAuthenticationError(
gitlab.exceptions.GitlabAuthenticationError: 401: 401 Unauthorized
```

I've verified token by cURL `curl --header "PRIVATE-TOKEN: $GITLAB_PAT" "https://gitlab.mycompany.com/api/v4/user"` and it worked. How can I solve the 401 Unauthorized problem?

**Comment by mrT23** [comment]
@rliskunov 
look at this public repo:
https://gitlab.com/doctorj/interview-questions/-/merge_requests/1

this now worked for me:
docker run --rm -it -e OPENAI.KEY=... -e CONFIG.GIT_PROVIDER=gitlab -e GITLAB.PERSONAL_ACCESS_TOKEN=... codiumai/pr-agent --pr_url https://gitlab.com/doctorj/interview-questions/-/merge_requests/1 review

It should also work for you. If not, you have a key issue

![image](https://github.com/Codium-ai/pr-agent/assets/21198860/524a0d6a-f70d-4197-bc6c-085fc1f25afd)

**Comment by rliskunov** [comment]
@mrT23 Thank you for your time! I found how to solve my problem

I need to set env variable `GITLAB.URL` with my url `https://gitlab.mycompany.com`. After that, everything work correctly. The full command looks like this
```
docker run --rm -it  \
  -e OPENAI.KEY=$OPENAI_KEY \
  -e CONFIG.GIT_PROVIDER=gitlab  \
  -e GITLAB.PERSONAL_ACCESS_TOKEN=$GITLAB_PAT \
  -e GITLAB.URL=https://gitlab.mycompany.com \
  codiumai/pr-agent:$TAG --pr_url $MR_URL review
```

**Comment by coditamar** [comment]
> @mrT23 Thank you for your time! I found how to solve my problem
> 
> I need to set env variable `GITLAB.URL` with my url `https://gitlab.mycompany.com`. After that, everything work correctly. The full command looks like this
> ```
> docker run --rm -it  \
>   -e OPENAI.KEY=$OPENAI_KEY \
>   -e CONFIG.GIT_PROVIDER=gitlab  \
>   -e GITLAB.PERSONAL_ACCESS_TOKEN=$GITLAB_PAT \
>   -e GITLAB.URL=https://gitlab.mycompany.com \
>   codiumai/pr-agent:$TAG --pr_url $MR_URL review
> ```

May I ask you to contribute a clarification to the GitLab installation ?
