### ISSUE TITLE
Gitlab - ERROR:root:Failed to parse AI prediction: while scanning a simple key

### ISSUE THREAD

**Issue by myvo** [Codium-ai/pr-agent#373]
```
ERROR:root:Failed to parse AI prediction: while scanning a simple key
  in "<unicode string>", line 14, column 5:
        ...
        ^
could not find expected ':'
  in "<unicode string>", line 15, column 5:
        relevant lines start: 290
        ^
INFO:root:Successfully parsed AI prediction after removing 107 lines
INFO:root:Pushing PR review...
INFO:root:Pushing inline code suggestions...
```
I got this error when I run `improve` command in Gitlab MR with 49 changed files.

**Comment by myvo** [comment]
And this error when I run `improve` command with some MR has only 1 changed file
```
ERROR:root:Could not publish code suggestion:
suggestion: {'body': "**Suggestion:** Remove unused code in the 'created' lifecycle hook\n```suggestion\n    // Remove unused code in the 'created' lifecycle hook\n    // ...\n```", 'relevant_file': 'myfil.vue', 'relevant_lines_start': 387, 'relevant_lines_end': 392}
error: 400: 400 Bad request - Note {:line_code=>["can't be blank", "must be a valid line code"]}
````

**Comment by mrT23** [comment]
There is no 100% success when working with AI models.
Sometimes the model fails to follow the instructions it is given (produce valid yaml, with valid MR lines).
Hence some suggestions may not be published. This is not necessarily a "bug".
We still provided informative log messages.

In any case, you have not provided any reproduction code.

**Comment by mrT23** [comment]
without a proper way to **debug** it, i cannot solve.
log message is not enough

try to provide a reproduction code.

**Comment by mrT23** [comment]
closing. welcome to share more details, and can re-open

**Comment by myvo** [comment]
With the latest code of pr-agent, I have the trace log now. 
```
2023-11-10 15:33:53.620 | INFO     | pr_agent.tools.pr_code_suggestions:_prepare_prediction:84 - Getting PR diff...
2023-11-10 15:33:53.736 | INFO     | pr_agent.tools.pr_code_suggestions:_prepare_prediction:91 - Getting AI prediction...
2023-11-10 15:34:07.969 | INFO     | pr_agent.algo.ai_handler:chat_completion:120 - AI response
2023-11-10 15:34:07.972 | INFO     | pr_agent.tools.pr_code_suggestions:run:76 - Pushing PR review...
2023-11-10 15:34:08.048 | INFO     | pr_agent.tools.pr_code_suggestions:run:78 - Pushing inline code suggestions...
2023-11-10 15:34:09.607 | ERROR    | pr_agent.git_providers.gitlab_provider:publish_code_suggestions:243 - Could not publish code suggestion:
suggestion: {'body': "**Suggestion:** Add error handling for failed API call\n```suggestion\n      if (res.err) {\n        this.$router.push(APP_ROUTES.AUTH_LOGIN);\n        this.$alertError(this.$t('page/auth/CompleteYourAccount/error/linkExpired'));\n      } else {\n        // Handle success case\n      }\n```", 'relevant_file': 'src/pages/Auth/CompleteYourAccount/CompleteYourAccount.vue', 'relevant_lines_start': 273, 'relevant_lines_end': 276}
error: 400: 400 Bad request - Note {:line_code=>["can't be blank", "must be a valid line code"]}
Traceback (most recent call last):

  File "/home/myvv/.local/lib/python3.10/site-packages/gitlab/exceptions.py", line 336, in wrapped_f
    return f(*args, **kwargs)
           │  │       └ {}
           │  └ (<gitlab.v4.objects.discussions.ProjectMergeRequestDiscussionManager object at 0x7f148c44d9c0>, {'body': "**Suggestion:** Add...
           └ <function CreateMixin.create at 0x7f148cff6200>
  File "/home/myvv/.local/lib/python3.10/site-packages/gitlab/mixins.py", line 300, in create
    server_data = self.gitlab.http_post(path, post_data=data, files=files, **kwargs)
                  │    │      │         │               │           │        └ {}
                  │    │      │         │               │           └ {}
                  │    │      │         │               └ {'body': "**Suggestion:** Add error handling for failed API call\n```suggestion:-0+3\n      if (res.err) {\n        this.$rou...
                  │    │      │         └ '/projects/896/merge_requests/3347/discussions'
                  │    │      └ <function Gitlab.http_post at 0x7f14bf9484c0>
                  │    └ <gitlab.client.Gitlab object at 0x7f148c632890>
                  └ <gitlab.v4.objects.discussions.ProjectMergeRequestDiscussionManager object at 0x7f148c44d9c0>
  File "/home/myvv/.local/lib/python3.10/site-packages/gitlab/client.py", line 1021, in http_post
    result = self.http_request(
             │    └ <function Gitlab.http_request at 0x7f14bf9481f0>
             └ <gitlab.client.Gitlab object at 0x7f148c632890>
  File "/home/myvv/.local/lib/python3.10/site-packages/gitlab/client.py", line 794, in http_request
    raise gitlab.exceptions.GitlabHttpError(
          │      │          └ <class 'gitlab.exceptions.GitlabHttpError'>
          │      └ <module 'gitlab.exceptions' from '/home/myvv/.local/lib/python3.10/site-packages/gitlab/exceptions.py'>
          └ <module 'gitlab' from '/home/myvv/.local/lib/python3.10/site-packages/gitlab/__init__.py'>

gitlab.exceptions.GitlabHttpError: 400: 400 Bad request - Note {:line_code=>["can't be blank", "must be a valid line code"]}
```
Thanks for your support!

**Comment by myvo** [comment]
And here is the log of my first issue with unicode:
```
2023-11-10 15:40:11.681 | INFO     | pr_agent.tools.pr_reviewer:_prepare_prediction:148 - Getting PR diff...
2023-11-10 15:40:11.826 | INFO     | pr_agent.tools.pr_reviewer:_prepare_prediction:150 - Getting AI prediction...
2023-11-10 15:40:22.343 | INFO     | pr_agent.algo.ai_handler:chat_completion:120 - AI response
2023-11-10 15:40:22.343 | INFO     | pr_agent.tools.pr_reviewer:run:114 - Preparing PR review...
2023-11-10 15:40:22.345 | ERROR    | pr_agent.algo.utils:load_yaml:294 - Failed to parse AI prediction: mapping values are not allowed here
  in "<unicode string>", line 14, column 32:
          relevant line: +  isReady: false,
                                   ^
2023-11-10 15:40:22.366 | INFO     | pr_agent.algo.utils:try_fix_yaml:305 - Successfully parsed AI prediction after removing 15 lines
2023-11-10 15:40:22.367 | INFO     | pr_agent.tools.pr_reviewer:run:118 - Pushing PR review...
```
Many thanks, @mrT23 !

**Comment by mrT23** [comment]
Hi @myvo 

The issue you encounter has nothing to do with 'Unicode characters'. It is a limitation of LLM, that don't always obey commands.

We specifically ask them to output yaml with [block scalar](https://yaml-multiline.info/#:~:text=Block%20Scalars,-A%20block%20scalar&text=If%20you%20would%20like%20them,by%20putting%20two%20newlines%20in.) format.

Most of the time they do that. Sometimes not.
When they don't, we experience problems with parsing their answers.

<img width="988" alt="image" src="https://github.com/Codium-ai/pr-agent/assets/21198860/b2be4b4c-52d7-4307-a246-c20cc643c43a">
<img width="993" alt="image" src="https://github.com/Codium-ai/pr-agent/assets/21198860/9e35c2ee-44d0-401f-95be-80df72c6f48b">

The error mechanism we have worked well - they disqualified just the suggestions (with the bad parsing), but output everything before. And we provide logs. The fact that the log says 'error' is just for emphasis. In practice, the error was watched and mitigated. I do believe you received an output.

Anyway, I open a PR with another fallback mechanism for your specific type of error:
https://github.com/Codium-ai/pr-agent/pull/444
if you are able to reproduce the issue, try to run with the PR, I think it will work.

In any case, remember - no 100% success all the time is guaranteed when working with LLMs.

**Comment by myvo** [comment]
Got it. Let me try to run the PR #444 
Many thanks @mrT23 !
