### ISSUE TITLE
pr_agent crash

### ISSUE THREAD

**Issue by ChrisWiles** [Codium-ai/pr-agent#486]
Seems a recent commit broke something. This worked yesterday.

```
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          config.max_model_tokens: 128000 # 128K context window for the GPT-4 Turbo model
          config.model: 'gpt-4-1106-preview'
          config.max_description_tokens: 1000 # max token length of the PR description
          config.max_commits_tokens: 500 # max token length for reading PR commits
          config.verbosity_level: 2 # 0 = silent, 1 = errors, 2 = warnings
          github_action.auto_describe: 'true' # Automatically describe the PR
          # github_action.auto_improve: 'true' # Automatically suggest code improvements
          github_action.auto_review: 'true' # Automatically review the PR
 ```

```
23:02:40.469 | INFO     | __main__:run_action:58 - enable_custom_labels: False
Traceback (most recent call last):
  File "/app/pr_agent/servers/github_action_runner.py", line 102, in <module>
    asyncio.run(run_action())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/pr_agent/servers/github_action_runner.py", line 68, in run_action
    auto_review = get_settings().get('GITHUB_ACTION.AUTO_REVIEW', None)
  File "/usr/local/lib/python3.10/site-packages/dynaconf/base.py", line 450, in get
    return self._dotted_get(
  File "/usr/local/lib/python3.10/site-packages/dynaconf/base.py", line 414, in _dotted_get
    return self._dotted_get(
  File "/usr/local/lib/python3.10/site-packages/dynaconf/base.py", line 403, in _dotted_get
    result = self.get(name, default=default, parent=parent, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dynaconf/base.py", line 477, in get
    data = (parent or self.store).get(key, default)
AttributeError: 'str' object has no attribute 'get'
```

![Screenshot 2023-11-28 at 5 11 46 PM](https://github.com/Codium-ai/pr-agent/assets/9455409/dd4f1070-c55b-4d0f-83d5-f4d0a393a221)

**Comment by mrT23** [comment]
@ChrisWiles Thanks for the feedback. We will investigate.
Our goal here was to be robust to capital letters.

**Comment by mrT23** [comment]
@ChrisWiles should be solve now
