### ISSUE TITLE
Requirements Pinecone Datasets

### ISSUE THREAD

**Issue by PrashantDixit0** [Codium-ai/pr-agent#544]
Failed to install Pinecone Dataset from `requirements.txt`.

Reporting error 

```
Resolved https://github.com/mrT23/pinecone-datasets.git to commit 9018d935d27e9bcc2b8de4c151228c60c6cc10da
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/usr/lib/python3/dist-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
        File "/usr/lib/python3/dist-packages/poetry/core/factory.py", line 43, in create_poetry
          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - Additional properties are not allowed ('group' was unexpected)
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by mrT23** [comment]
`pip install -r requirement.txt ` works. the docker gets built

dont use poetry for pr-agent.
