### ISSUE TITLE
Failes to process Azure DevOps PR URLs that include spaces

### ISSUE THREAD

**Issue by danstis** [Codium-ai/pr-agent#740]
When attempting to run against an Azure DevOps URL that includes an URL encoded space (%20), PR Agent fails with a 404 error.
This is an issue when the Azure DevOps project name contains a space.

For example when running the Azure DevOps Webhook tag:
```
INFO:     172.20.0.2:55368 - "POST / HTTP/1.1" 202 Accepted
2024-03-05 02:34:30.642 | INFO     | pr_agent.agent.pr_agent:handle_request:77 - PR-Agent request handler started
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette_context/middleware/raw_middleware.py", line 92, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 174, in __call__
    await self.background()
  File "/usr/local/lib/python3.10/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/usr/local/lib/python3.10/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/app/pr_agent/agent/pr_agent.py", line 90, in handle_request
    await command2class[action](pr_url, ai_handler=self.ai_handler, args=args).run()
  File "/app/pr_agent/tools/pr_description.py", line 31, in __init__
    self.git_provider = get_git_provider()(pr_url)
  File "/app/pr_agent/git_providers/azuredevops_provider.py", line 54, in __init__
    self.set_pr(pr_url)
  File "/app/pr_agent/git_providers/azuredevops_provider.py", line 189, in set_pr
    self.pr = self._get_pr()
  File "/app/pr_agent/git_providers/azuredevops_provider.py", line 550, in _get_pr
    self.pr = self.azure_devops_client.get_pull_request_by_id(
  File "/usr/local/lib/python3.10/site-packages/azure/devops/v7_0/git/git_client_base.py", line 2066, in get_pull_request_by_id
    response = self._send(http_method='GET',
  File "/usr/local/lib/python3.10/site-packages/azure/devops/client.py", line 104, in _send
    response = self._send_request(request=request, headers=headers, content=content, media_type=media_type)
  File "/usr/local/lib/python3.10/site-packages/azure/devops/client.py", line 68, in _send_request
    self._handle_error(request, response)
  File "/usr/local/lib/python3.10/site-packages/azure/devops/client.py", line 294, in _handle_error
    raise AzureDevOpsClientRequestError(full_message_format.format(error_message=error_message,
azure.devops.exceptions.AzureDevOpsClientRequestError: Operation returned a 404 status code.
```

This also happens in the docker CLI version of PR Agent, with the same error:
```
Traceback (most recent call last):
  File "/app/pr_agent/cli.py", line 68, in <module>
    run()
  File "/app/pr_agent/cli.py", line 62, in run
    result = asyncio.run(PRAgent().handle_request(args.pr_url, [command] + args.rest))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/pr_agent/agent/pr_agent.py", line 87, in handle_request
    await command2class[action](pr_url, ai_handler=self.ai_handler, args=args).run()
  File "/app/pr_agent/tools/pr_description.py", line 31, in __init__
    self.git_provider = get_git_provider()(pr_url)
  File "/app/pr_agent/git_providers/azuredevops_provider.py", line 51, in __init__
    self.set_pr(pr_url)
  File "/app/pr_agent/git_providers/azuredevops_provider.py", line 186, in set_pr
    self.pr = self._get_pr()
  File "/app/pr_agent/git_providers/azuredevops_provider.py", line 530, in _get_pr
    self.pr = self.azure_devops_client.get_pull_request_by_id(
  File "/usr/local/lib/python3.10/site-packages/azure/devops/v7_0/git/git_client_base.py", line 2066, in get_pull_request_by_id
    response = self._send(http_method='GET',
  File "/usr/local/lib/python3.10/site-packages/azure/devops/client.py", line 104, in _send
    response = self._send_request(request=request, headers=headers, content=content, media_type=media_type)
  File "/usr/local/lib/python3.10/site-packages/azure/devops/client.py", line 68, in _send_request
    self._handle_error(request, response)
  File "/usr/local/lib/python3.10/site-packages/azure/devops/client.py", line 294, in _handle_error
    raise AzureDevOpsClientRequestError(full_message_format.format(error_message=error_message,
azure.devops.exceptions.AzureDevOpsClientRequestError: Operation returned a 404 status code.
```

If I force the URL to be decoded before processing then it works as expected.
For example in the file `pr_agent/servers/azuredevops_server_webhook.py`:
```python
from urllib.parse import unquote
...

pr_url = unquote(data["resource"]["_links"]["web"]["href"].replace("_apis/git/repositories", "_git"))
```

**Comment by mrT23** [comment]
feel free to open a PR to address this
