### ISSUE TITLE
'summarize_mode' is undefined

### ISSUE THREAD

**Issue by ChrisWiles** [Codium-ai/pr-agent#869]
pr_agent crashing suddenly was there a change with `summarize_mode`?

```
Traceback (most recent call last):
  File "/app/pr_agent/servers/github_action_runner.py", line 148, in <module>
    asyncio.run(run_action())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/pr_agent/servers/github_action_runner.py", line 106, in run_action
    await PRCodeSuggestions(pr_url).run()
  File "/app/pr_agent/tools/pr_code_suggestions.py", line 64, in __init__
    self.token_handler = TokenHandler(self.git_provider.pr,
  File "/app/pr_agent/algo/token_handler.py", line 49, in __init__
    self.prompt_tokens = self._get_system_user_tokens(pr, self.encoder, vars, system, user)
  File "/app/pr_agent/algo/token_handler.py", line 66, in _get_system_user_tokens
    system_prompt = environment.from_string(system).render(vars)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 56, in top-level template code
jinja2.exceptions.UndefinedError: 'summarize_mode' is undefined
```

Also my `extra_instructions` don't work anymore
```yaml
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml
          config.max_model_tokens: 128000 # 128K context window for the GPT-4 Turbo model
          config.model: 'gpt-4-1106-preview'
          config.max_description_tokens: 1000 # max token length of the PR description
          config.max_commits_tokens: 500 # max token length for reading PR commits
          config.verbosity_level: 2 # 0 = silent, 1 = errors, 2 = warnings
          github_action.auto_describe: 'true' # Automatically describe the PR
          # github_action.auto_improve: 'true' # Automatically suggest code improvements
          github_action.auto_review: 'true' # Automatically review the PR
          pr_description.add_original_user_description: 'true' # Add the original user description to the PR description
          # pr_description.keep_original_user_title: 'true'
          # pr_description.publish_description_as_comment: 'true'
          pr_description.extra_instructions: ''
          pr_reviewer.enable_review_labels_effort: 'true'
          pr_reviewer.extra_instructions: ${{ env.decoded_instructions }}
          pr_reviewer.num_code_suggestions: 8 # Number of code suggestions to provide, default is 4
          pr_reviewer.minimal_minutes_for_incremental_review: 720 # 12 hours, only rereview PR that have had 12 hours since the last review
```

I tried asking this question in discord but was banned immediately... unban me please?

![Screenshot 2024-04-17 at 3 58 18 PM](https://github.com/Codium-ai/pr-agent/assets/9455409/41ab7b9d-8389-421b-a4b9-bdeb810d6bcc)

**Comment by khanzzirfan** [comment]
same here +1

**Comment by yeosu0107** [comment]
same +1

**Comment by mrT23** [comment]
We changed the name yesterday from

'summarize= true'
to
**'commitable_code_suggestions = false'**

Guess we should have added backward compatibility.
will try to add one now, but use the new name, its more expressive

**Comment by mrT23** [comment]
fixing...

**Comment by mrT23** [comment]
@ChrisWiles sorry for that, should be fixed now

**Comment by barnett-yuxiang** [comment]
👍
