### ISSUE TITLE
UTF-8 undecodable files checked in breaks commands 

### ISSUE THREAD

**Issue by BadLiveware** [Codium-ai/pr-agent#915]
Certain commands break when the change contains UTF-8 undecodable files, specifically gzipped tar archives in this case. 

`/describe`, `/review` break completely while `/improve` still works but will log warnings(likely not a problem)

Running `0.22-gitlab_webhook`

```
Cannot decode file kubernetes/base/applications/geo/prod/charts/app-0.0.1.tgz or kubernetes/base/applications/geo/prod/charts/app-0.0.1.tgz in merge request 24149

Failed to generate prediction with gpt-4: Traceback (most recent call last):
  File "/app/pr_agent/algo/pr_processing.py", line 272, in retry_with_fallback_models
    return await f(model)
  File "/app/pr_agent/tools/pr_description.py", line 167, in _prepare_prediction
    self.patches_diff = get_pr_diff(self.git_provider, self.token_handler, model)
  File "/app/pr_agent/algo/pr_processing.py", line 78, in get_pr_diff
    patches_extended, total_tokens, patches_extended_tokens = pr_generate_extended_diff(
  File "/app/pr_agent/algo/pr_processing.py", line 148, in pr_generate_extended_diff
    extended_patch = extend_patch(original_file_content_str, patch, num_lines=patch_extra_lines)
  File "/app/pr_agent/algo/git_patch_processing.py", line 26, in extend_patch
    original_file_str = original_file_str.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by mrT23** [comment]
Thanks @BadLiveware 

You are welcome to try and debug it if you have the motivation, and open a PR.

I will add it to our tasks list, but I can't guarantee it will be prioritized.

**Comment by mrT23** [comment]
this should solved the issue:
https://github.com/Codium-ai/pr-agent/pull/918

try again against the latest docker

`codiumai/pr-agent:gitlab_webhook`

**Comment by BadLiveware** [comment]
It does work on `codiumai/pr-agent:gitlab_webhook`

**Comment by mrT23** [comment]
great
