### ISSUE TITLE
[GitLab] 401: Unauthorized on random MRs

### ISSUE THREAD

**Issue by OctavioCore** [Codium-ai/pr-agent#922]
Hi,
I've run into a 401 on GitLab SaaS - but weirdly it only occurred on a single MR. Another MR in the same repository works as expected, with literally the same tokens.

Our setup is pretty direct - we're using the `codiumai/pr_agent` Docker image directly in the CI/CD pipeline, templating the config files beforehand, during the job execution. Got rid of DIND that way.

The only difference in the MR URLs is the ID, so nothing unexpected. The MRs are triggered by different users - but as the token does not belong to either of them (Those tokens belong to service accounts - they have appropriate access and membership), shouldn't be the issue. The job that fails does not work even with my own admin-level PAT, with the same error code.

Do you have any ideas on why the agent would behave differently in two jobs in the same project, on the same credentials?

Here's the traceback:
```
Traceback (most recent call last):
  File "/app/pr_agent/cli.py", line 80, in <module>
    run()
  File "/app/pr_agent/cli.py", line 74, in run
    result = asyncio.run(PRAgent().handle_request(args.pr_url, [command] + args.rest))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/pr_agent/agent/pr_agent.py", line 93, in handle_request
    await command2class[action](pr_url, ai_handler=self.ai_handler, args=args).run()
  File "/app/pr_agent/tools/pr_description.py", line 31, in __init__
    self.git_provider = get_git_provider()(pr_url)
  File "/app/pr_agent/git_providers/gitlab_provider.py", line 41, in __init__
    self._set_merge_request(merge_request_url)
  File "/app/pr_agent/git_providers/gitlab_provider.py", line 58, in _set_merge_request
    self.mr = self._get_merge_request()
  File "/app/pr_agent/git_providers/gitlab_provider.py", line 406, in _get_merge_request
    mr = self.gl.projects.get(self.id_project).mergerequests.get(self.id_mr)
  File "/usr/local/lib/python3.10/site-packages/gitlab/v4/objects/projects.py", line 860, in get
    return cast(Project, super().get(id=id, lazy=lazy, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/gitlab/exceptions.py", line 336, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gitlab/mixins.py", line 122, in get
    server_data = self.gitlab.http_get(path, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gitlab/client.py", line 828, in http_get
    result = self.http_request(
  File "/usr/local/lib/python3.10/site-packages/gitlab/client.py", line 788, in http_request
    raise gitlab.exceptions.GitlabAuthenticationError(
gitlab.exceptions.GitlabAuthenticationError: 401: 401 Unauthorized

**Comment by mrT23** [comment]
Deploying to GitLab is fairly complicated, and requires time, DevOps skills, and solving problems that may arise.

We did it ourselves, and wrote a guide that described our "journey". Many people were able to follow it, and self-deploy.

However, we cant provide QA and debug for each self-depolyment.  

You are welcome to try pr-agent-pro, where installation on gitlab is just a single click. 

Another option is try to ask the community. I won't close this issue, so other users may help.

all the best
